---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ohaiibuzzle-ublue-elysia
# description will be included in the image's metadata
description: ElysiaOS, but it's uBlue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - ublue-os/staging
        - che/nerd-fonts
        - solopasha/hyprland
        - brycensranch/gpu-screen-recorder-git
        - scottames/awww
    install:
      packages:
        - micro
        - starship
        - git
        - thunar
        - btop
        - eww
        - fastfetch
        - gpu-screen-recorder-ui
        - hyprland
        - kitty
        - NetworkManager
        - rofi
        - curl
        - wget
        - swaync
        - waybar
        - wlogout
        - sddm
        - plymouth
        - fontconfig
        - awww

  - type: script
    scripts:
      - elysia.sh

  - type: default-flatpaks@v2
    configurations: 
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        repo:
          title: Flathub (system)
        install:
          - one.ablaze.floorp
          - com.visualstudio.code-oss
          - com.github.tchx84.Flatseal
          - io.github.dvlv.boxbuddyrs
      - scope: user
        repo:
          title: Flathub (user)


  - type: signing # this sets up the proper policy & signing files for signed images to work fully
