---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ohaiibuzzle-ublue-elysia
# description will be included in the image's metadata
description: ElysiaOS, but it's uBlue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - ublue-os/staging
        - ublue-os/packages
        - che/nerd-fonts
        - solopasha/hyprland
        - brycensranch/gpu-screen-recorder-git
        - scottames/awww
        - eddsalkield/swaylock-effects
        - atim/ubuntu-fonts
    install:
      packages:
        - micro
        - starship
        - flatpak
        - vulkan
        - wireplumber
        - firewalld
        - nerd-fonts
        - git
        - thunar
        - xfce4-settings 
        - xfce4-taskmanager
        - btop
        - eww
        - fastfetch
        - gpu-screen-recorder-ui
        - hyprland
        # - hyprland-qt-support
        - hyprlock
        - hyprpicker
        - hyprutils
        # - hyprswitch
        - kitty
        - NetworkManager
        - rofi
        - curl
        - wget
        - swaync
        - waybar
        - wlogout
        - sddm
        - plymouth
        - fontconfig
        - awww
        - ublue-brew
        - grubby
        - xdg-user-dirs
        - xdg-desktop-portal
        - xdg-desktop-portal-wlr
        - xdg-desktop-portal-hyprland
        - xdg-desktop-portal-gnome
        - gnome-text-editor
        - flameshot
        - playerctl
        - grim
        - lm_sensors
        - libnotify
        - fcitx5
        - copyq
        - gsettings-desktop-schemas
        - qt5-qtbase
        - qt5-qtmultimedia
        - qt5-qtsvg
        - qt5-qtwayland
        - qt5ct
        - qt6-qtbase
        - qt6-qtwayland
        - qt6ct
        - google-noto-fonts-all
        - xclip
        - wl-clipboard
        # - clipnotify
        - brightnessctl
        - zip
        - libzip
        - file-roller
        - unzip
        - thunar-archive-plugin
        - swaylock-effects
        - python3
        - python3-cairo
        - python3-installer
        - python3-numpy
        - python3-pillow
        - python3-pip
        - python3-psutil
        - python3-qt5
        - python3-pyqt6
        - python3-qt5-webengine
        - python3-pyqt6-sip
        - python3-pyqt5-sip
        - python3-tqdm
        # - xkb-switch
        - pipewire-pulseaudio
        - jetbrains-mono-fonts-all
        - granite
        - qimgv
        - sxiv
        - libhandy
        - python3-pypresence
        - xhost
        - polkit
        - mate-polkit
        # - polkit-gnome
        # - polkit-qt6
        - ffmpegthumbnailer
        - tumbler
        - slurp
        - bc
        - coreutils
        - dmenu
        - dejavu-fonts-all
        - ubuntu-family-fonts
        - sil-doulos-fonts
        - hanamin-fonts 
        - sazanami-fonts-all
        - baekmuk-ttf-fonts-all
        - cjkuni-uming-fonts 
        - fcitx5-configtool
        - fcitx5-mozc
        - mpv
        - jq
        - ffmpeg
        - gstreamer1-plugin-libav
        - qt6-qtmultimedia
        - gparted

  - type: script
    scripts:
      - elysia.sh

  - type: default-flatpaks@v2
    configurations: 
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        repo:
          title: Flathub (system)
        install:
          - one.ablaze.floorp
          - com.google.Chrome
          - com.visualstudio.code-oss
          - dev.vencord.Vesktop
          - com.valvesoftware.Steam
          - com.github.tchx84.Flatseal
          - io.github.dvlv.boxbuddyrs
      - scope: user
        repo:
          title: Flathub (user)


  - type: signing # this sets up the proper policy & signing files for signed images to work fully
